name: Deploy Angular to GH Pages

on:
  push:
    branches: [ main ]  # publica a cada push na main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --force

      - name: Build (base-href para subpasta do repo)
        run: npm run build -- --configuration production --base-href=/poc-camera/

      # SPA fallback: copia index.html para 404.html (evita 404 no refresh)
      - name: SPA fallback
        run: |
          cp dist/camera-test-laudo/index.html dist/camera-test-laudo/404.html || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/camera-test-laudo